/*  _____ _______         _                      _
 * |_   _|__   __|       | |                    | |
 *   | |    | |_ __   ___| |___      _____  _ __| | __  ___ ____
 *   | |    | | '_ \ / _ \ __\ \ /\ / / _ \| '__| |/ / / __|_  /
 *  _| |_   | | | | |  __/ |_ \ V  V / (_) | |  |   < | (__ / /
 * |_____|  |_|_| |_|\___|\__| \_/\_/ \___/|_|  |_|\_(_)___/___|
 *                                _
 *              ___ ___ ___ _____|_|_ _ _____
 *             | . |  _| -_|     | | | |     |  LICENCE
 *             |  _|_| |___|_|_|_|_|___|_|_|_|
 *             |_|
 *
 *   PROGRAMOVÁNÍ  <>  DESIGN  <>  PRÁCE/PODNIKÁNÍ  <>  HW A SW
 *
 * Tento zdrojový kód je součástí výukových seriálů na
 * IT sociální síti WWW.ITNETWORK.CZ
 *
 * Kód spadá pod licenci prémiového obsahu a vznikl díky podpoře
 * našich členů. Je určen pouze pro osobní užití a nesmí být šířen.
 * Více informací na http://www.itnetwork.cz/licence
 */
package cz.itnetwork.entity;

import cz.itnetwork.constant.Countries;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.util.List;

/**
 * Entity class representing a person in the database.
 * This class uses the Lombok library to automatically generate getters and setters.
 * Each person can be linked to multiple invoices, represented through the One-to-Many relationships with {@link InvoiceEntity}.
 */
@Entity(name = "person")
@Getter
@Setter
public class PersonEntity {
    /**
     * The unique identifier for the person, automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The name of the person, a mandatory attribute.
     */
    @Column(nullable = false)
    private String name;

    /**
     * Identification number of the person, a mandatory attribute used for unique identification in business transactions.
     */
    @Column(nullable = false)
    private String identificationNumber;

    /**
     * Tax number of the person, optional and used for tax purposes.
     */
    private String taxNumber;

    /**
     * Account number of the person, mandatory for financial transactions.
     */
    @Column(nullable = false)
    private String accountNumber;

    /**
     * Bank code associated with the person's account, mandatory for identifying the bank in transactions.
     */
    @Column(nullable = false)
    private String bankCode;

    /**
     * IBAN number, optional and used for international financial transactions.
     */
    private String iban;

    /**
     * Telephone number of the person, a mandatory attribute.
     */
    @Column(nullable = false)
    private String telephone;

    /**
     * Email address of the person, a mandatory attribute.
     */
    @Column(nullable = false)
    private String mail;

    /**
     * Street address of the person, a mandatory attribute.
     */
    @Column(nullable = false)
    private String street;

    /**
     * ZIP or postal code of the person, a mandatory attribute.
     */
    @Column(nullable = false)
    private String zip;

    /**
     * City of residence of the person, a mandatory attribute.
     */
    @Column(nullable = false)
    private String city;

    /**
     * Country of residence of the person, represented as an enum and a mandatory attribute.
     */
    @Column(nullable = false)
    @Enumerated(EnumType.STRING)
    private Countries country;

    /**
     * Optional note related to the person.
     */
    private String note;

    /**
     * Flag indicating whether the person's information should be hidden, default is false.
     */
    private boolean hidden = false;
}